import type { DashboardData, SnapshotDetail, SnapshotSummary } from "./types";

const capturedAt = "2026-09-01T08:00:00.000Z";

const latest: SnapshotDetail = {
  id: "demo-snapshot-4",
  baseSnapshotId: "demo-snapshot-3",
  capturedAt,
  rawInput: "這是範例資料，不代表任何真實使用者",
  totalCashTwd: "340000",
  totalSecuritiesTwd: "1006000",
  totalAssetValueTwd: "1346000",
  totalLiabilitiesTwd: "60000",
  totalCreditCardLiabilitiesTwd: "24000",
  totalCreditCardCreditsTwd: "0",
  netWorthTwd: "1286000",
  totalCostTwd: "900000",
  unrealizedPnlTwd: "106000",
  accounts: [
    {
      accountId: "demo-living",
      name: "生活帳戶",
      institution: "範例銀行",
      accountType: "bank",
      accountReference: "1234",
      defaultCurrency: "TWD",
      cashBalances: [{ currency: "TWD", amount: "85000" }],
      positions: [],
      loans: [],
    },
    {
      accountId: "demo-emergency",
      name: "緊急預備金",
      institution: "範例銀行",
      accountType: "bank",
      accountReference: "5678",
      defaultCurrency: "TWD",
      cashBalances: [{ currency: "TWD", amount: "180000" }],
      positions: [],
      loans: [],
    },
    {
      accountId: "demo-broker",
      name: "長期投資帳戶",
      institution: "範例證券",
      accountType: "brokerage",
      accountReference: "2468",
      defaultCurrency: "TWD",
      cashBalances: [{ currency: "TWD", amount: "75000" }],
      positions: [
        {
          id: "demo-position-tw",
          positionId: "demo-position-tw",
          securityId: "demo-security-tw",
          accountId: "demo-broker",
          accountName: "長期投資帳戶",
          market: "TWSE",
          exchange: "TWSE",
          symbol: "0050",
          name: "範例臺灣 ETF",
          securityType: "etf",
          quoteCurrency: "TWD",
          quantity: "2000",
          averageCost: "150",
          marketPrice: "180",
          quoteAsOf: capturedAt,
          quoteSource: "MANUAL",
          quoteStatus: "manual",
          costValueTwd: "300000",
          marketValueTwd: "360000",
          unrealizedPnlTwd: "60000",
          unrealizedReturnPct: "20",
        },
        {
          id: "demo-position-global",
          positionId: "demo-position-global",
          securityId: "demo-security-global",
          accountId: "demo-broker",
          accountName: "長期投資帳戶",
          market: "US",
          exchange: "NYSE Arca",
          symbol: "VT",
          name: "範例全球股票 ETF",
          securityType: "etf",
          quoteCurrency: "USD",
          quantity: "100",
          averageCost: "185.7585",
          marketPrice: "200",
          quoteAsOf: capturedAt,
          quoteSource: "MANUAL",
          quoteStatus: "manual",
          fxRate: {
            baseCurrency: "USD",
            quoteCurrency: "TWD",
            rate: "32.3",
            rateAsOf: capturedAt,
            source: "MANUAL",
            status: "manual",
            overriddenByUser: false,
          },
          costValueTwd: "600000",
          marketValueTwd: "646000",
          unrealizedPnlTwd: "46000",
          unrealizedReturnPct: "7.6667",
        },
      ],
      loans: [],
    },
  ],
  loans: [
    {
      id: "demo-loan",
      loanId: "demo-loan",
      name: "範例分期",
      institution: "範例銀行",
      loanType: "personal",
      currency: "TWD",
      originalPrincipal: "60000",
      outstandingPrincipal: "36000",
      annualInterestRate: "2.5",
      rateType: "fixed",
      monthlyPayment: "3000",
      paymentDayOfMonth: 15,
      nextPaymentDate: "2026-09-15",
      valueTwd: "36000",
    },
  ],
  creditCardAccounts: [
    {
      id: "demo-card-account",
      creditCardAccountId: "demo-card-account",
      name: "日常消費卡",
      issuer: "範例銀行",
      currency: "TWD",
      sharedCreditLimit: "200000",
      statementDayOfMonth: 25,
      paymentDayOfMonth: 18,
      status: "active",
      cards: [
        {
          cardId: "demo-card",
          name: "現金回饋卡",
          lastFour: "8888",
          network: "visa",
          holderType: "primary",
          status: "active",
        },
      ],
      statementPeriod: "2026-08",
      statementDate: "2026-08-25",
      dueDate: "2026-09-18",
      statementAmount: "24000",
      paymentAmount: "0",
      paymentDate: null,
      remainingInstallmentPrincipal: "0",
      overpaymentBalance: "0",
      statementOutstanding: "24000",
      utilizationPct: "12",
      paymentStatus: "unpaid",
      paidOnTime: null,
      statementAmountTwd: "24000",
      liabilityValueTwd: "24000",
      creditAssetValueTwd: "0",
    },
  ],
  cashFlows: [],
  changeBreakdown: {
    previousNetWorthTwd: "1200000",
    netWorthChangeTwd: "86000",
    assetChangeTwd: "92000",
    liabilityReductionTwd: "6000",
    capitalContributionTwd: "30000",
    capitalWithdrawalTwd: "0",
    incomeTwd: "6000",
    feeTaxTwd: "1000",
    otherNetFlowTwd: "0",
    marketAndFxTwd: "51000",
  },
};

const historyPoint = (
  id: string,
  date: string,
  assets: string,
  liabilities: string,
  netWorth: string,
): SnapshotSummary => ({
  id,
  capturedAt: date,
  rawInput: "範例快照",
  totalCashTwd: "300000",
  totalSecuritiesTwd: String(Number(assets) - 300000),
  totalAssetValueTwd: assets,
  totalLiabilitiesTwd: liabilities,
  totalCreditCardLiabilitiesTwd: "0",
  totalCreditCardCreditsTwd: "0",
  netWorthTwd: netWorth,
  totalCostTwd: "850000",
  unrealizedPnlTwd: String(Number(assets) - 1150000),
});

const history = [
  historyPoint(
    "demo-snapshot-1",
    "2026-03-01T08:00:00.000Z",
    "1080000",
    "80000",
    "1000000",
  ),
  historyPoint(
    "demo-snapshot-2",
    "2026-05-01T08:00:00.000Z",
    "1175000",
    "70000",
    "1105000",
  ),
  historyPoint(
    "demo-snapshot-3",
    "2026-07-01T08:00:00.000Z",
    "1266000",
    "66000",
    "1200000",
  ),
  latest,
];

export const demoDashboardData: DashboardData = {
  latest,
  history,
  trend: history.map((item) => ({
    capturedAt: item.capturedAt,
    totalAssetValueTwd: item.netWorthTwd,
  })),
  sold: [],
  health: {
    lastUpdatedAt: capturedAt,
    daysSinceUpdate: 0,
    freshnessTone: "fresh",
    freshnessLabel: "範例資料",
    shouldWarnOnOpen: false,
    findings: [],
  },
};
